import { Inter } from "next/font/google";
import "./globals.css";
import "./axiosSetup"; // Import axios setup to initialize it

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Taskify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="root">{children}</div>
      </body>
    </html>
  );
}
